name: Lint
on:
  pull_request:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: Linting
        uses: kairos-io/linting-composite-action@v0.0.2
